theme = "coder" # set the theme
title = "Dan Trickey"

[params] # theme parameters
    author = "Dan Trickey" # author's name
    info = "I write code" # author's job title or info
    description = "Dan's personal website" # site description
    keywords = "blog,developer,personal" # site keywords

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/trickeydan/"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/trickeydan/"

# Menu links
[[menu.main]]
    name = "About Me"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Blog"
    weight = 4
    url  = "/posts/"
[[menu.main]]
    name = "Contact"
    weight = 5
    url  = "/contact/"
