theme = "coder" # set the theme
title = "Dan Trickey"

[params] # theme parameters
    author = "Dan Trickey" # author's name
    info = "I write code." # author's job title or info
    description = "Dan's personal website" # site description
    keywords = "blog,developer,personal" # site keywords

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/trickeydan/"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/trickeydan/"

# Menu links
[[menu.main]]
    name = "Home"
    weight = 1
    url  = "/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
